# -*- coding: utf-8 -*-

A1_ALPHABETICAL_DECKS = {
    "A1 Seviyesi - A Harfi Destesi": [
        {"word": "About", "meaning": "Hakkında", "example_sentence": "Tell me about your family. | Bana ailen hakkında anlat."},
        {"word": "Above", "meaning": "Üzerinde", "example_sentence": "The sky is above us. | Gökyüzü üzerimizdedir."},
        {"word": "Across", "meaning": "Karşısında / Karşıdan karşıya", "example_sentence": "They walked across the street. | Caddenin karşısına yürüdüler."},
        {"word": "Act", "meaning": "Rol yapmak / Davranmak", "example_sentence": "He acts in the school play. | Okul oyununda rol alıyor."},
        {"word": "Action", "meaning": "Eylem / Aksiyon", "example_sentence": "I love action movies. | Aksiyon filmlerini severim."},
        {"word": "Activity", "meaning": "Aktivite", "example_sentence": "Football is a fun activity. | Futbol eğlenceli bir aktivitedir."},
        {"word": "Actor", "meaning": "Erkek Oyuncu", "example_sentence": "He is a famous actor. | O ünlü bir oyuncudur."},
        {"word": "Actress", "meaning": "Kadın Oyuncu", "example_sentence": "She is a talented actress. | O yetenekli bir oyuncudur."},
        {"word": "Add", "meaning": "Eklemek", "example_sentence": "Add some sugar to my tea. | Çayıma biraz şeker ekle."},
        {"word": "Address", "meaning": "Adres", "example_sentence": "What is your home address? | Ev adresiniz nedir?"},
        {"word": "Adult", "meaning": "Yetişkin", "example_sentence": "This film is for adults. | Bu film yetişkinler içindir."},
        {"word": "Advice", "meaning": "Tavsiye", "example_sentence": "He gave me good advice. | Bana iyi bir tavsiye verdi."},
        {"word": "Afraid", "meaning": "Korkmuş", "example_sentence": "She is afraid of dogs. | Köpeklerden korkar."},
        {"word": "After", "meaning": "Sonra", "example_sentence": "We play after school. | Okuldan sonra oynarız."},
        {"word": "Afternoon", "meaning": "Öğleden sonra", "example_sentence": "See you this afternoon. | Bu öğleden sonra görüşürüz."},
        {"word": "Again", "meaning": "Tekrar", "example_sentence": "Please read the text again. | Lütfen metni tekrar okuyun."},
        {"word": "Age", "meaning": "Yaş", "example_sentence": "What is your age? | Yaşınız kaçtır?"},
        {"word": "Ago", "meaning": "Önce", "example_sentence": "I met him two days ago. | Onunla iki gün önce tanıştım."},
        {"word": "Agree", "meaning": "Aynı fikirde olmak", "example_sentence": "I agree with you. | Seninle aynı fikirdeyim."},
        {"word": "Air", "meaning": "Hava", "example_sentence": "The air is very cold today. | Bugün hava çok soğuk."},
        {"word": "Airport", "meaning": "Havalimanı", "example_sentence": "The plane landed at the airport. | Uçak havalimanına indi."},
        {"word": "All", "meaning": "Hepsi / Tüm", "example_sentence": "All students are here. | Tüm öğrenciler burada."},
        {"word": "Also", "meaning": "Ayrıca / Hem de", "example_sentence": "He is also a doctor. | O aynı zamanda bir doktordur."},
        {"word": "Always", "meaning": "Her zaman", "example_sentence": "She always wakes up early. | O her zaman erken uyanır."},
        {"word": "Amazing", "meaning": "Harika / Şaşırtıcı", "example_sentence": "This view is amazing. | Bu manzara harika."},
        {"word": "Angry", "meaning": "Kızgın", "example_sentence": "The teacher was angry with us. | Öğretmen bize kızgındı."},
        {"word": "Animal", "meaning": "Hayvan", "example_sentence": "A lion is a wild animal. | Aslan vahşi bir hayvandır."},
        {"word": "Another", "meaning": "Başka / Diğer", "example_sentence": "I want another cup of tea. | Bir fincan çay daha istiyorum."},
        {"word": "Answer", "meaning": "Cevap", "example_sentence": "Please answer the question. | Lütfen soruyu cevaplayın."},
        {"word": "Any", "meaning": "Hiç / Herhangi", "example_sentence": "Do you have any questions? | Hiç sorunuz var mı?"},
        {"word": "Anyone", "meaning": "Kimse / Herhangi biri", "example_sentence": "Is anyone in the room? | Odada kimse var mı?"},
        {"word": "Anything", "meaning": "Hiçbir şey / Herhangi bir şey", "example_sentence": "I don't need anything. | Hiçbir şeye ihtiyacım yok."},
        {"word": "Apartment", "meaning": "Daire / Apartman", "example_sentence": "They live in a small apartment. | Küçük bir dairede yaşıyorlar."},
        {"word": "Apple", "meaning": "Elma", "example_sentence": "I eat a red apple. | Kırmızı bir elma yerim."},
        {"word": "Area", "meaning": "Alan / Bölge", "example_sentence": "The play area is very clean. | Oyun alanı çok temiz."},
        {"word": "Arm", "meaning": "Kol", "example_sentence": "He broke his arm. | Kolunu kırdı."},
        {"word": "Around", "meaning": "Etrafında / Çevresinde", "example_sentence": "They walked around the park. | Parkın etrafında yürüdüler."},
        {"word": "Arrive", "meaning": "Varmak / Ulaşmak", "example_sentence": "The train arrives at six. | Tren saat altıda varıyor."},
        {"word": "Art", "meaning": "Sanat", "example_sentence": "I love modern art. | Modern sanatı severim."},
        {"word": "Article", "meaning": "Makale / Yazı", "example_sentence": "He wrote a new article. | Yeni bir makale yazdı."},
        {"word": "Artist", "meaning": "Sanatçı", "example_sentence": "She is a professional artist. | O profesyonel bir sanatçıdır."},
        {"word": "As", "meaning": "Gibi / Olarak", "example_sentence": "He works as a teacher. | Öğretmen olarak çalışıyor."},
        {"word": "Ask", "meaning": "Sormak", "example_sentence": "Ask him for help. | Ondan yardım iste."},
        {"word": "At", "meaning": "-de, -da", "example_sentence": "She is at school right now. | Şu anda okulda."},
        {"word": "August", "meaning": "Ağustos", "example_sentence": "August is a hot month. | Ağustos sıcak bir aydır."},
        {"word": "Aunt", "meaning": "Teyze / Hala", "example_sentence": "My aunt lives in London. | Teyzem Londra'da yaşıyor."},
        {"word": "Autumn", "meaning": "Sonbahar", "example_sentence": "Leaves fall in autumn. | Sonbaharda yapraklar dökülür."},
        {"word": "Away", "meaning": "Uzakta / Uzağa", "example_sentence": "Go away from here. | Buradan uzağa git."}
    ],
    "A1 Seviyesi - B Harfi Destesi": [
        {"word": "Baby", "meaning": "Bebek", "example_sentence": "The baby is sleeping. | Bebek uyuyor."},
        {"word": "Back", "meaning": "Geri / Arka", "example_sentence": "Come back home. | Eve geri dön."},
        {"word": "Bad", "meaning": "Kötü", "example_sentence": "This is a bad idea. | Bu kötü bir fikir."},
        {"word": "Bag", "meaning": "Çanta", "example_sentence": "My school bag is heavy. | Okul çantam ağır."},
        {"word": "Ball", "meaning": "Top", "example_sentence": "Throw the ball to me. | Topu bana at."},
        {"word": "Banana", "meaning": "Muz", "example_sentence": "I like eating bananas. | Muz yemeyi severim."},
        {"word": "Band", "meaning": "Grup / Bando", "example_sentence": "My brother plays in a rock band. | Erkek kardeşim bir rock grubunda çalıyor."},
        {"word": "Bank", "meaning": "Banka", "example_sentence": "The bank opens at nine. | Banka dokuzda açılıyor."},
        {"word": "Bar", "meaning": "Bar / Büfe", "example_sentence": "We met at a coffee bar. | Bir kahve barında buluştuk."},
        {"word": "Baseball", "meaning": "Beyzbol", "example_sentence": "He plays baseball on Saturdays. | Cumartesi günleri beyzbol oynar."},
        {"word": "Basketball", "meaning": "Basketbol", "example_sentence": "They play basketball after school. | Okuldan sonra basketbol oynarlar."},
        {"word": "Bath", "meaning": "Banyo / Yıkanma", "example_sentence": "She takes a hot bath. | Sıcak bir banyo yapıyor."},
        {"word": "Bathroom", "meaning": "Banyo (Oda)", "example_sentence": "The bathroom is very clean. | Banyo çok temiz."},
        {"word": "Be", "meaning": "Olmak", "example_sentence": "I want to be a doctor. | Doktor olmak istiyorum."},
        {"word": "Beach", "meaning": "Sahil / Plaj", "example_sentence": "We walk on the sandy beach. | Kumsal sahilde yürüyoruz."},
        {"word": "Beautiful", "meaning": "Güzel", "example_sentence": "She has beautiful eyes. | Güzel gözleri var."},
        {"word": "Because", "meaning": "Çünkü", "example_sentence": "I study because I have an exam. | Çalışıyorum çünkü sınavım var."},
        {"word": "Become", "meaning": "Olmak / Dönüşmek", "example_sentence": "Caterpillars become butterflies. | Tırtıllar kelebeğe dönüşür."},
        {"word": "Bed", "meaning": "Yatak", "example_sentence": "I go to bed at ten. | Saat onda yatağa giderim."},
        {"word": "Bedroom", "meaning": "Yatak Odası", "example_sentence": "My bedroom has a big window. | Yatak odamın büyük bir penceresi var."},
        {"word": "Beer", "meaning": "Bira", "example_sentence": "He drinks a cold beer. | Soğuk bir bira içiyor."},
        {"word": "Before", "meaning": "Önce", "example_sentence": "Wash your hands before dinner. | Akşam yemeğinden önce ellerini yıka."},
        {"word": "Begin", "meaning": "Başlamak", "example_sentence": "The film begins now. | Film şimdi başlıyor."},
        {"word": "Beginning", "meaning": "Başlangıç / Baş", "example_sentence": "This is the beginning of the story. | Bu hikayenin başlangıcı."},
        {"word": "Behind", "meaning": "Arkada / Arkasında", "example_sentence": "The cat is behind the door. | Kedi kapının arkasında."},
        {"word": "Believe", "meaning": "İnanmak", "example_sentence": "I believe you. | Sana inanıyorum."},
        {"word": "Below", "meaning": "Altında", "example_sentence": "Read the text below. | Aşağıdaki metni okuyun."},
        {"word": "Beside", "meaning": "Yanında / Yanı başında", "example_sentence": "Sit beside me. | Yanıma otur."},
        {"word": "Best", "meaning": "En iyi", "example_sentence": "He is my best friend. | O benim en iyi arkadaşım."},
        {"word": "Better", "meaning": "Daha iyi", "example_sentence": "I feel better today. | Bugün daha iyi hissediyorum."},
        {"word": "Between", "meaning": "Arasında", "example_sentence": "The apple is between the boxes. | Elma kutuların arasında."},
        {"word": "Bicycle/Bike", "meaning": "Bisiklet", "example_sentence": "I ride my bike to school. | Okula bisikletimle giderim."},
        {"word": "Big", "meaning": "Büyük", "example_sentence": "They live in a big house. | Büyük bir evde yaşıyorlar."},
        {"word": "Bill", "meaning": "Fatura", "example_sentence": "Please pay the phone bill. | Lütfen telefon faturasını öde."},
        {"word": "Bird", "meaning": "Kuş", "example_sentence": "A bird is singing on the tree. | Ağaçta bir kuş ötüyor."},
        {"word": "Birthday", "meaning": "Doğum günü", "example_sentence": "Tomorrow is my birthday. | Yarın benim doğum günüm."},
        {"word": "Black", "meaning": "Siyah", "example_sentence": "She wore a black dress. | Siyah bir elbise giydi."},
        {"word": "Blog", "meaning": "Blog", "example_sentence": "He writes a travel blog. | Bir seyahat blogu yazıyor."},
        {"word": "Blonde", "meaning": "Sarışın", "example_sentence": "She has blonde hair. | Onun sarı saçları var."},
        {"word": "Blue", "meaning": "Mavi", "example_sentence": "The sky is blue today. | Bugün gökyüzü mavi."},
        {"word": "Boat", "meaning": "Tekne / Bot", "example_sentence": "They rent a boat for the trip. | Gezi için bir tekne kiraladılar."},
        {"word": "Body", "meaning": "Vücut / Beden", "example_sentence": "Exercise is good for the body. | Egzersiz vücut için iyidir."},
        {"word": "Book", "meaning": "Kitap", "example_sentence": "I read an interesting book. | İlginç bir kitap okudum."},
        {"word": "Boot", "meaning": "Bot / Çizme", "example_sentence": "Wear boots in winter. | Kışın bot giy."},
        {"word": "Bored", "meaning": "Sıkılmış", "example_sentence": "I am bored in this lesson. | Bu derste sıkıldım."},
        {"word": "Boring", "meaning": "Sıkıcı", "example_sentence": "This movie is very boring. | Bu film çok sıkıcı."},
        {"word": "Born", "meaning": "Doğmuş", "example_sentence": "I was born in Istanbul. | İstanbul'da doğdum."},
        {"word": "Both", "meaning": "Her ikisi", "example_sentence": "Both of my sisters are students. | Kız kardeşlerimin her ikisi de öğrencidir."},
        {"word": "Bottle", "meaning": "Şişe", "example_sentence": "Give me a bottle of water. | Bana bir şişe su ver."},
        {"word": "Box", "meaning": "Kutu", "example_sentence": "The toys are in the box. | Oyuncaklar kutunun içinde."},
        {"word": "Boy", "meaning": "Erkek Çocuk", "example_sentence": "The boy is playing football. | Erkek çocuk futbol oynuyor."},
        {"word": "Bread", "meaning": "Ekmek", "example_sentence": "I buy fresh bread. | Taze ekmek alırım."},
        {"word": "Break", "meaning": "Kırmak / Mola", "example_sentence": "We have a short break. | Kısa bir molamız var."},
        {"word": "Breakfast", "meaning": "Kahvaltı", "example_sentence": "I eat eggs for breakfast. | Kahvaltıda yumurta yerim."},
        {"word": "Bring", "meaning": "Getirmek", "example_sentence": "Bring me your notebook. | Bana defterini getir."},
        {"word": "Brother", "meaning": "Erkek Kardeş", "example_sentence": "My brother is older than me. | Erkek kardeşim benden büyük."},
        {"word": "Brown", "meaning": "Kahverengi", "example_sentence": "The horse is brown. | At kahverengidir."},
        {"word": "Build", "meaning": "İnşa etmek", "example_sentence": "They build a new house. | Yeni bir ev inşa ediyorlar."},
        {"word": "Building", "meaning": "Bina", "example_sentence": "This is a tall building. | Bu yüksek bir binadır."},
        {"word": "Bus", "meaning": "Otobüs", "example_sentence": "I go to school by bus. | Okula otobüsle giderim."},
        {"word": "Business", "meaning": "İş / Ticaret", "example_sentence": "He has a small business. | Küçük bir işi var."},
        {"word": "Businessman", "meaning": "İş adamı", "example_sentence": "My father is a businessman. | Babam bir iş adamıdır."},
        {"word": "Businesswoman", "meaning": "İş kadını", "example_sentence": "My mother is a businesswoman. | Annem bir iş kadınıdır."},
        {"word": "Busy", "meaning": "Meşgul", "example_sentence": "I am very busy today. | Bugün çok meşgulüm."},
        {"word": "But", "meaning": "Ama / Fakat", "example_sentence": "I want to go, but I can't. | Gitmek istiyorum ama gidemem."},
        {"word": "Butter", "meaning": "Tereyağı", "example_sentence": "Spread butter on the bread. | Ekmeğe tereyağı sür."},
        {"word": "Buy", "meaning": "Satın almak", "example_sentence": "I want to buy a new shirt. | Yeni bir gömlek satın almak istiyorum."},
        {"word": "By", "meaning": "Tarafından / İle", "example_sentence": "This book was written by him. | Bu kitap onun tarafından yazıldı."},
        {"word": "Bye", "meaning": "Hoşça kal", "example_sentence": "Bye, see you tomorrow! | Hoşça kal, yarın görüşürüz!"}
    ],
    "A1 Seviyesi - C Harfi Destesi": [
        {"word": "Cafe", "meaning": "Kafe", "example_sentence": "Let's meet at the cafe. | Kafede buluşalım."},
        {"word": "Cake", "meaning": "Kek / Pasta", "example_sentence": "She baked a chocolate cake. | Çikolatalı bir kek pişirdi."},
        {"word": "Call", "meaning": "Aramak / Çağırmak", "example_sentence": "Call me this evening. | Beni bu akşam ara."},
        {"word": "Camera", "meaning": "Kamera", "example_sentence": "I take photos with my camera. | Kameramla fotoğraflar çekerim."},
        {"word": "Camp", "meaning": "Kamp", "example_sentence": "We go to summer camp. | Yaz kampına gideriz."},
        {"word": "Can", "meaning": "Ebilmek / Yapabilmek", "example_sentence": "I can swim very well. | Çok iyi yüzebilirim."},
        {"word": "Capital", "meaning": "Başkent", "example_sentence": "London is the capital of England. | Londra, İngiltere'nin başkentidir."},
        {"word": "Car", "meaning": "Araba", "example_sentence": "He drives a blue car. | Mavi bir araba sürüyor."},
        {"word": "Card", "meaning": "Kart", "example_sentence": "He wrote a birthday card. | Bir doğum günü kartı yazdı."},
        {"word": "Career", "meaning": "Kariyer", "example_sentence": "She wants a successful career. | Başarılı bir kariyer istiyor."},
        {"word": "Carrot", "meaning": "Havuç", "example_sentence": "Rabbits love eating carrots. | Tavşanlar havuç yemeyi sever."},
        {"word": "Carry", "meaning": "Taşımak", "example_sentence": "He carries a heavy box. | Ağır bir kutu taşıyor."},
        {"word": "Cat", "meaning": "Kedi", "example_sentence": "The cat is on the table. | Kedi masanın üstünde."},
        {"word": "Case", "meaning": "Vaka / Kasa / Durum", "example_sentence": "In this case, we should wait. | Bu durumda beklemeliyiz."},
        {"word": "Catch", "meaning": "Yakalamak", "example_sentence": "Catch the ball! | Topu yakala!"},
        {"word": "CD", "meaning": "Müzik Diski (CD)", "example_sentence": "I listen to a music CD. | Bir müzik CD'si dinliyorum."},
        {"word": "Center", "meaning": "Merkez", "example_sentence": "The hotel is in the city center. | Otel şehir merkezindedir."},
        {"word": "Centimeter", "meaning": "Santimetre", "example_sentence": "A ruler is thirty centimeters long. | Bir cetvel otuz santimetre uzunluğundadır."},
        {"word": "Century", "meaning": "Yüzyıl", "example_sentence": "We live in the 21st century. | 21. yüzyılda yaşıyoruz."},
        {"word": "Chair", "meaning": "Sandalye", "example_sentence": "Sit on the comfortable chair. | Rahat sandalyeye otur."},
        {"word": "Change", "meaning": "Değiştirmek / Değişim", "example_sentence": "Can you change this bill? | Bu faturayı değiştirebilir misiniz?"},
        {"word": "Channel", "meaning": "Kanal", "example_sentence": "Turn to the news channel. | Haber kanalını aç."},
        {"word": "Chat", "meaning": "Sohbet etmek", "example_sentence": "They chat on the phone. | Telefonda sohbet ediyorlar."},
        {"word": "Cheap", "meaning": "Ucuz", "example_sentence": "This T-shirt is very cheap. | Bu tişört çok ucuz."},
        {"word": "Check", "meaning": "Kontrol etmek", "example_sentence": "Please check your answers. | Lütfen cevaplarınızı kontrol edin."},
        {"word": "Cheese", "meaning": "Peynir", "example_sentence": "I eat cheese at breakfast. | Kahvaltıda peynir yerim."},
        {"word": "Chef", "meaning": "Şef / Aşçı", "example_sentence": "The chef prepares delicious food. | Şef lezzetli yemekler hazırlar."},
        {"word": "Chicken", "meaning": "Tavuk", "example_sentence": "The chicken is in the garden. | Tavuk bahçededir."},
        {"word": "Child", "meaning": "Çocuk", "example_sentence": "The child is drawing a picture. | Çocuk resim çiziyor."},
        {"word": "Chocolate", "meaning": "Çikolata", "example_sentence": "I love milk chocolate. | Sütlü çikolatayı severim."},
        {"word": "Choose", "meaning": "Seçmek", "example_sentence": "Choose your favorite color. | En sevdiğin rengi seç."},
        {"word": "Cinema", "meaning": "Sinema", "example_sentence": "We go to the cinema on Fridays. | Cuma günleri sinemaya gideriz."},
        {"word": "City", "meaning": "Şehir", "example_sentence": "Paris is a beautiful city. | Paris güzel bir şehirdir."},
        {"word": "Class", "meaning": "Sınıf / Ders", "example_sentence": "We are in the same class. | Aynı sınıftayız."},
        {"word": "Classroom", "meaning": "Sınıf (Oda)", "example_sentence": "The classroom has a smart board. | Sınıfta akıllı tahta var."},
        {"word": "Clean", "meaning": "Temiz / Temizlemek", "example_sentence": "Please clean your room. | Lütfen odanı temizle."},
        {"word": "Clear", "meaning": "Açık / Net", "example_sentence": "The sky is very clear today. | Bugün gökyüzü çok açık."},
        {"word": "Clever", "meaning": "Zeki", "example_sentence": "She is a clever student. | O zeki bir öğrencidir."},
        {"word": "Clock", "meaning": "Saat", "example_sentence": "The wall clock is slow. | Duvar saati geri kalmış."},
        {"word": "Close", "meaning": "Kapatmak / Yakın", "example_sentence": "Please close the door. | Lütfen kapıyı kapat."},
        {"word": "Closed", "meaning": "Kapalı", "example_sentence": "The shop is closed on Sundays. | Dükkan Pazar günleri kapalıdır."},
        {"word": "Clothes", "meaning": "Kıyafetler", "example_sentence": "Put your clothes in the wardrobe. | Kıyafetlerini gardıroba koy."},
        {"word": "Club", "meaning": "Kulüp", "example_sentence": "I joined the chess club. | Satranç kulübüne katıldım."},
        {"word": "Coat", "meaning": "Kaban / Palto", "example_sentence": "Wear a warm coat. | Sıcak bir kaban giy."},
        {"word": "Coffee", "meaning": "Kahve", "example_sentence": "I drink coffee in the morning. | Sabahleyin kahve içerim."},
        {"word": "Cold", "meaning": "Soğuk", "example_sentence": "The weather is very cold. | Hava çok soğuk."},
        {"word": "College", "meaning": "Kolej / Yüksekokul", "example_sentence": "He studies engineering at college. | Kolejde mühendislik okuyor."},
        {"word": "Color", "meaning": "Renk", "example_sentence": "What color is your car? | Arabanızın rengi nedir?"},
        {"word": "Come", "meaning": "Gelmek", "example_sentence": "Come here, please. | Buraya gel lütfen."},
        {"word": "Common", "meaning": "Ortak / Yaygın", "example_sentence": "We share a common goal. | Ortak bir hedefi paylaşıyoruz."},
        {"word": "Company", "meaning": "Şirket", "example_sentence": "He works at a software company. | Bir yazılım şirketinde çalışıyor."},
        {"word": "Compare", "meaning": "Karşılaştırmak", "example_sentence": "Compare these two books. | Bu iki kitabı karşılaştırın."},
        {"word": "Complete", "meaning": "Tamamlamak", "example_sentence": "Complete the sentences. | Cümleleri tamamlayın."},
        {"word": "Computer", "meaning": "Bilgisayar", "example_sentence": "I use a computer for my work. | İşim için bilgisayar kullanırım."},
        {"word": "Concert", "meaning": "Konser", "example_sentence": "They went to a rock concert. | Bir rock konserine gittiler."},
        {"word": "Conversation", "meaning": "Sohbet / Konuşma", "example_sentence": "We had a long conversation. | Uzun bir sohbet ettik."},
        {"word": "Cook", "meaning": "Pişirmek / Aşçı", "example_sentence": "My mother cooks dinner. | Annem akşam yemeğini pişiriyor."},
        {"word": "Cooking", "meaning": "Yemek Pişirme", "example_sentence": "Cooking is my hobby. | Yemek pişirmek benim hobimdir."},
        {"word": "Cool", "meaning": "Serin / Harika", "example_sentence": "It gets cool in the evening. | Akşamları serin oluyor."},
        {"word": "Corner", "meaning": "Köşe", "example_sentence": "The shop is on the corner. | Dükkan köşededir."},
        {"word": "Correct", "meaning": "Doğru", "example_sentence": "Your answer is correct. | Cevabınız doğru."},
        {"word": "Cost", "meaning": "Maliyet / Fiyatı Olmak", "example_sentence": "How much does it cost? | Bunun fiyatı ne kadar?"},
        {"word": "Country", "meaning": "Ülke", "example_sentence": "Which country are you from? | Hangi ülkedensiniz?"},
        {"word": "Course", "meaning": "Kurs / Ders", "example_sentence": "I am taking an English course. | İngilizce kursu alıyorum."},
        {"word": "Cousin", "meaning": "Kuzen", "example_sentence": "My cousin is visiting us. | Kuzenim bizi ziyaret ediyor."},
        {"word": "Cow", "meaning": "İnek", "example_sentence": "The cow gives fresh milk. | İnek taze süt verir."},
        {"word": "Credit card", "meaning": "Kredi Kartı", "example_sentence": "Can I pay by credit card? | Kredi kartıyla ödeyebilir miyim?"},
        {"word": "Cross", "meaning": "Karşıya geçmek", "example_sentence": "Cross the street carefully. | Caddeden dikkatlice karşıya geç."},
        {"word": "Cry", "meaning": "Ağlamak", "example_sentence": "Don't cry, everything is fine. | Ağlama, her şey yolunda."},
        {"word": "Cup", "meaning": "Fincan / Kupa", "example_sentence": "I drink a cup of tea. | Bir fincan çay içerim."},
        {"word": "Customer", "meaning": "Müşteri", "example_sentence": "The customer is always right. | Müşteri her zaman haklıdır."},
        {"word": "Cut", "meaning": "Kesmek", "example_sentence": "Cut the cake into pieces. | Pastayı dilimlere kes."},
        {"word": "Cycle", "meaning": "Bisiklete binmek", "example_sentence": "We cycle in the forest. | Ormanda bisiklete bineriz."}
    ],
    "A1 Seviyesi - D, E, F Harfleri Destesi": [
        {"word": "Dad/Daddy", "meaning": "Baba / Babacık", "example_sentence": "My dad helps me with my homework. | Babam ödevlerime yardım eder."},
        {"word": "Daily", "meaning": "Günlük", "example_sentence": "Reading is a daily habit. | Okumak günlük bir alışkanlıktır."},
        {"word": "Dance", "meaning": "Dans etmek / Dans", "example_sentence": "We love to dance at parties. | Partilerde dans etmeyi severiz."},
        {"word": "Dancer", "meaning": "Dansçı", "example_sentence": "She is a professional dancer. | O profesyonel bir dansçıdır."},
        {"word": "Dancing", "meaning": "Dans Etme", "example_sentence": "Dancing makes me happy. | Dans etmek beni mutlu eder."},
        {"word": "Dangerous", "meaning": "Tehlikeli", "example_sentence": "Playing in the street is dangerous. | Sokakta oynamak tehlikelidir."},
        {"word": "Dark", "meaning": "Karanlık", "example_sentence": "The room is dark, turn on the light. | Oda karanlık, ışığı aç."},
        {"word": "Date", "meaning": "Tarih / Randevu", "example_sentence": "What is the date today? | Bugünün tarihi nedir?"},
        {"word": "Daughter", "meaning": "Kız Evlat", "example_sentence": "They have one daughter. | Bir kız evlatları var."},
        {"word": "Day", "meaning": "Gün", "example_sentence": "It is a sunny day today. | Bugün güneşli bir gün."},
        {"word": "Dear", "meaning": "Sevgili", "example_sentence": "Dear friend, thank you for the letter. | Sevgili arkadaşım, mektup için teşekkürler."},
        {"word": "December", "meaning": "Aralık (Ay)", "example_sentence": "December is the last month of the year. | Aralık yılın son ayıdır."},
        {"word": "Decide", "meaning": "Karar vermek", "example_sentence": "Decide what you want to eat. | Ne yemek istediğine karar ver."},
        {"word": "Delicious", "meaning": "Lezzetli", "example_sentence": "The soup is delicious. | Çorba lezzetlidir."},
        {"word": "Dentist", "meaning": "Diş hekimi", "example_sentence": "I go to the dentist every year. | Her yıl diş hekimine giderim."},
        {"word": "Department store", "meaning": "Büyük Mağaza / Alışveriş Merkezi", "example_sentence": "I bought this jacket at the department store. | Bu ceketi büyük mağazadan aldım."},
        {"word": "Describe", "meaning": "Tanımlamak / Tarif etmek", "example_sentence": "Describe your new car. | Yeni arabanızı tarif edin."},
        {"word": "Desk", "meaning": "Sıra / Çalışma Masası", "example_sentence": "Put the book on the desk. | Kitabı çalışma masasının üzerine koy."},
        {"word": "Dessert", "meaning": "Tatlı", "example_sentence": "We had cake for dessert. | Tatlı olarak pasta yedik."},
        {"word": "Detail", "meaning": "Detay", "example_sentence": "Please explain in detail. | Lütfen detaylı olarak açıklayın."},
        {"word": "Diary", "meaning": "Günlük / Ajanda", "example_sentence": "She writes in her diary every night. | Her gece günlüğüne yazar."},
        {"word": "Dictionary", "meaning": "Sözlük", "example_sentence": "Use a dictionary for new words. | Yeni kelimeler için bir sözlük kullan."},
        {"word": "Die", "meaning": "Ölmek", "example_sentence": "Plants die without water. | Bitkiler susuz ölür."},
        {"word": "Diet", "meaning": "Diyet", "example_sentence": "She is on a healthy diet. | Sağlıklı bir diyettedir."},
        {"word": "Difference", "meaning": "Fark", "example_sentence": "What is the difference between these? | Bunların arasındaki fark nedir?"},
        {"word": "Different", "meaning": "Farklı", "example_sentence": "They are from different cities. | Farklı şehirlerdendirler."},
        {"word": "Difficult", "meaning": "Zor", "example_sentence": "This is a difficult test. | Bu zor bir sınavdır."},
        {"word": "Dinner", "meaning": "Akşam Yemeği", "example_sentence": "We eat dinner at seven. | Akşam yemeğini yedide yeriz."},
        {"word": "Early", "meaning": "Erken", "example_sentence": "He arrived early for the meeting. | Toplantıya erken geldi."},
        {"word": "East", "meaning": "Doğu", "example_sentence": "The sun rises in the east. | Güneş doğudan doğar."},
        {"word": "Easy", "meaning": "Kolay", "example_sentence": "This game is very easy. | Bu oyun çok kolaydır."},
        {"word": "Eat", "meaning": "Yemek yemek", "example_sentence": "We eat fresh fruit. | Taze meyve yeriz."},
        {"word": "Egg", "meaning": "Yumurta", "example_sentence": "I eat an egg for breakfast. | Kahvaltıda bir yumurta yerim."}
    ]
}
