"""add streak and target fields

Revision ID: 5477d7b79deb
Revises: 0eaff3e2b883
Create Date: 2026-05-29 09:54:39.800907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5477d7b79deb'
down_revision = '0eaff3e2b883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_target', sa.Integer(), server_default='10', nullable=False))
        batch_op.add_column(sa.Column('daily_progress', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_progress')
        batch_op.drop_column('daily_target')
        batch_op.drop_column('last_activity_date')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
